-- MySQL Script generated by MySQL Workbench
-- Sat Jun 22 21:22:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lto_actmanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lto_actmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lto_actmanager` DEFAULT CHARACTER SET utf8 ;
USE `lto_actmanager` ;

-- -----------------------------------------------------
-- Table `lto_actmanager`.`compania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`compania` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`compania` (
  `idCompania` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `rfc` VARCHAR(20) NULL,
  `domicilio` VARCHAR(400) NULL,
  `telefono` VARCHAR(30) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`area` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`area` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(150) NULL,
  `descripcion` VARCHAR(400) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idArea`, `idCompania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`proyecto` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`persona` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`persona` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `apellidoPaterno` VARCHAR(150) NOT NULL,
  `apellidoMaterno` VARCHAR(150) NULL,
  `email` VARCHAR(200) NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`personaAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`personaAtencion` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`personaAtencion` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`actividad` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`actividad` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idActividadPadre` INT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `categoria` INT NOT NULL,
  `tiempoProgramado` INT NOT NULL,
  `tiempoReal` INT NOT NULL,
  `orden` INT NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`actividadPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`actividadPersona` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`actividadPersona` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `tipo`, `idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`agenda` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`agenda` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idAgenda` INT NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `repetir` INT NOT NULL,
  `periodicidad` INT NULL,
  `valorPeriodicidad` VARCHAR(30) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `idAgenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`actividadBitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`actividadBitacora` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`actividadBitacora` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idActividadBitacora` INT NOT NULL,
  `estatus` INT NOT NULL,
  `fecMov` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `idActividadBitacora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lto_actmanager`.`estatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lto_actmanager`.`estatus` ;

CREATE TABLE IF NOT EXISTS `lto_actmanager`.`estatus` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idEstatus` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idEstatus`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
