-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 10:54:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`compania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compania` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compania` (
  `idCompania` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `rfc` VARCHAR(20) NULL,
  `domicilio` VARCHAR(400) NULL,
  `telefono` VARCHAR(30) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(150) NULL,
  `descripcion` VARCHAR(400) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idArea`, `idCompania`),
  CONSTRAINT `fk_area_compania`
    FOREIGN KEY (`idCompania`)
    REFERENCES `mydb`.`compania` (`idCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_area_compania_idx` ON `mydb`.`area` (`idCompania` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`),
  CONSTRAINT `fk_proyecto_area1`
    FOREIGN KEY (`idArea` , `idCompania`)
    REFERENCES `mydb`.`area` (`idArea` , `idCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proyecto_area1_idx` ON `mydb`.`proyecto` (`idArea` ASC, `idCompania` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `apellidoPaterno` VARCHAR(150) NOT NULL,
  `apellidoMaterno` VARCHAR(150) NULL,
  `email` VARCHAR(200) NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idPersona`),
  CONSTRAINT `fk_persona_area1`
    FOREIGN KEY (`idArea` , `idCompania`)
    REFERENCES `mydb`.`area` (`idArea` , `idCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_persona_area1_idx` ON `mydb`.`persona` (`idArea` ASC, `idCompania` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`personaAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personaAtencion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personaAtencion` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idPersona`),
  CONSTRAINT `fk_personaAtencion_proyecto1`
    FOREIGN KEY (`idCompania` , `idArea` , `idProyecto`)
    REFERENCES `mydb`.`proyecto` (`idCompania` , `idArea` , `idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personaAtencion_persona1`
    FOREIGN KEY (`idCompania` , `idArea` , `idPersona`)
    REFERENCES `mydb`.`persona` (`idCompania` , `idArea` , `idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_personaAtencion_persona1_idx` ON `mydb`.`personaAtencion` (`idCompania` ASC, `idArea` ASC, `idPersona` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idActividadPadre` INT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `categoria` INT NOT NULL,
  `tiempoProgramado` INT NOT NULL,
  `tiempoReal` INT NOT NULL,
  `orden` INT NOT NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`),
  CONSTRAINT `fk_actividad_proyecto1`
    FOREIGN KEY (`idCompania` , `idArea` , `idProyecto`)
    REFERENCES `mydb`.`proyecto` (`idCompania` , `idArea` , `idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actividad_proyecto1_idx` ON `mydb`.`actividad` (`idCompania` ASC, `idArea` ASC, `idProyecto` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`actividadPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividadPersona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividadPersona` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `tipo`, `idPersona`),
  CONSTRAINT `fk_actividadPersona_actividad1`
    FOREIGN KEY (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    REFERENCES `mydb`.`actividad` (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividadPersona_personaAtencion1`
    FOREIGN KEY (`idPersona` , `idCompania` , `idArea` , `idProyecto`)
    REFERENCES `mydb`.`personaAtencion` (`idPersona` , `idCompania` , `idArea` , `idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actividadPersona_personaAtencion1_idx` ON `mydb`.`actividadPersona` (`idPersona` ASC, `idCompania` ASC, `idArea` ASC, `idProyecto` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agenda` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idAgenda` INT NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `repetir` INT NOT NULL,
  `periodicidad` INT NULL,
  `valorPeriodicidad` VARCHAR(30) NULL,
  `estatus` INT NOT NULL,
  `fecMod` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `idAgenda`),
  CONSTRAINT `fk_agenda_actividad1`
    FOREIGN KEY (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    REFERENCES `mydb`.`actividad` (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_agenda_actividad1_idx` ON `mydb`.`agenda` (`idCompania` ASC, `idArea` ASC, `idProyecto` ASC, `idActividad` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`actividadBitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividadBitacora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividadBitacora` (
  `idCompania` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `idActividad` INT NOT NULL,
  `idActividadBitacora` INT NOT NULL,
  `estatus` INT NOT NULL,
  `fecMov` DATETIME NOT NULL,
  `usuCve` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCompania`, `idArea`, `idProyecto`, `idActividad`, `idActividadBitacora`),
  CONSTRAINT `fk_actividadBitacora_actividad1`
    FOREIGN KEY (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    REFERENCES `mydb`.`actividad` (`idCompania` , `idArea` , `idProyecto` , `idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actividadBitacora_actividad1_idx` ON `mydb`.`actividadBitacora` (`idCompania` ASC, `idArea` ASC, `idProyecto` ASC, `idActividad` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
